version: "3.8"

services:
  app:
    container_name: hobbit-dev
#    image: app-dev
    build:
      context: .
      target: development
    volumes:
      - ./public:/app/public
      - ./src:/app/src
    ports:
      - "3000:3000"